var expeditions = [{"Continent":"Africa","Research Type":"Wildlife & Ecosystems","Activity Level":"Easy","Title":"ANIMALS OF MALAWI IN THE MAJETE WILDLIFE RESERVE","Short Description":"How can we best help African wildlife return to and thrive in their native habitat?","Image Name":"img1.jpg","US Price Range":3725,"UK Price Range":4125,"Location":"Majete Wildlife Reserve, Malawi","Duration":12,"Boating":1,"Digging":1,"Diving":1,"Flat Land Hiking":1,"Snorkeling":1,"Swimming":null,"Uphill Hiking":null},
{"Continent":"Africa","Research Type":"Wildlife & Ecosystems","Activity Level":"Very Easy","Title":"ANIMALS OF MALAWI IN THE MAJETE WILDLIFE RESERVE","Short Description":"How can we best help African wildlife return to and thrive in their native habitat?","Image Name":"img1.jpg","US Price Range":3725,"UK Price Range":4125,"Location":"Majete Wildlife Reserve, Malawi","Duration":12,"Boating":null,"Digging":null,"Diving":null,"Flat Land Hiking":1,"Snorkeling":1,"Swimming":1,"Uphill Hiking":null},
{"Continent":"Africa","Research Type":"Wildlife & Ecosystems","Activity Level":"Moderate","Title":"ANIMALS OF MALAWI IN THE MAJETE WILDLIFE RESERVE","Short Description":"How can we best help African wildlife return to and thrive in their native habitat?","Image Name":"img1.jpg","US Price Range":3725,"UK Price Range":4125,"Location":"Majete Wildlife Reserve, Malawi","Duration":12,"Boating":null,"Digging":null,"Diving":null,"Flat Land Hiking":null,"Snorkeling":null,"Swimming":1,"Uphill Hiking":1},
{"Continent":"Africa","Research Type":"Wildlife & Ecosystems","Activity Level":"Strenuous","Title":"ANIMALS OF MALAWI IN THE MAJETE WILDLIFE RESERVE","Short Description":"How can we best help African wildlife return to and thrive in their native habitat?","Image Name":"img1.jpg","US Price Range":3725,"UK Price Range":4125,"Location":"Majete Wildlife Reserve, Malawi","Duration":12,"Boating":null,"Digging":null,"Diving":null,"Flat Land Hiking":null,"Snorkeling":null,"Swimming":null,"Uphill Hiking":null},
{"Continent":"Africa","Research Type":"Wildlife & Ecosystems","Activity Level":"Very Active","Title":"ANIMALS OF MALAWI IN THE MAJETE WILDLIFE RESERVE","Short Description":"How can we best help African wildlife return to and thrive in their native habitat?","Image Name":"img1.jpg","US Price Range":3725,"UK Price Range":4125,"Location":"Majete Wildlife Reserve, Malawi","Duration":12,"Boating":null,"Digging":null,"Diving":null,"Flat Land Hiking":null,"Snorkeling":1,"Swimming":1,"Uphill Hiking":1},
{"Continent":"Africa","Research Type":"Ocean Health","Activity Level":"Easy","Title":"ANIMALS OF MALAWI IN THE MAJETE WILDLIFE RESERVE","Short Description":"How can we best help African wildlife return to and thrive in their native habitat?","Image Name":"img1.jpg","US Price Range":3725,"UK Price Range":4125,"Location":"Majete Wildlife Reserve, Malawi","Duration":12,"Boating":null,"Digging":1,"Diving":1,"Flat Land Hiking":1,"Snorkeling":null,"Swimming":null,"Uphill Hiking":null},
{"Continent":"Africa","Research Type":"Ocean Health","Activity Level":"Very Easy","Title":"ANIMALS OF MALAWI IN THE MAJETE WILDLIFE RESERVE","Short Description":"How can we best help African wildlife return to and thrive in their native habitat?","Image Name":"img1.jpg","US Price Range":3725,"UK Price Range":4125,"Location":"Majete Wildlife Reserve, Malawi","Duration":12,"Boating":null,"Digging":null,"Diving":null,"Flat Land Hiking":1,"Snorkeling":1,"Swimming":1,"Uphill Hiking":null},
{"Continent":"Africa","Research Type":"Ocean Health","Activity Level":"Moderate","Title":"ANIMALS OF MALAWI IN THE MAJETE WILDLIFE RESERVE","Short Description":"How can we best help African wildlife return to and thrive in their native habitat?","Image Name":"img1.jpg","US Price Range":3725,"UK Price Range":4125,"Location":"Majete Wildlife Reserve, Malawi","Duration":12,"Boating":null,"Digging":null,"Diving":null,"Flat Land Hiking":null,"Snorkeling":null,"Swimming":null,"Uphill Hiking":1},
{"Continent":"Africa","Research Type":"Ocean Health","Activity Level":"Strenuous","Title":"ANIMALS OF MALAWI IN THE MAJETE WILDLIFE RESERVE","Short Description":"How can we best help African wildlife return to and thrive in their native habitat?","Image Name":"img1.jpg","US Price Range":3725,"UK Price Range":4125,"Location":"Majete Wildlife Reserve, Malawi","Duration":12,"Boating":null,"Digging":1,"Diving":1,"Flat Land Hiking":1,"Snorkeling":null,"Swimming":null,"Uphill Hiking":null},
{"Continent":"Africa","Research Type":"Ocean Health","Activity Level":"Very Active","Title":"ANIMALS OF MALAWI IN THE MAJETE WILDLIFE RESERVE","Short Description":"How can we best help African wildlife return to and thrive in their native habitat?","Image Name":"img1.jpg","US Price Range":3725,"UK Price Range":4125,"Location":"Majete Wildlife Reserve, Malawi","Duration":12,"Boating":1,"Digging":1,"Diving":1,"Flat Land Hiking":null,"Snorkeling":null,"Swimming":null,"Uphill Hiking":null},
{"Continent":"Africa","Research Type":"Climate Change","Activity Level":"Easy","Title":"ANIMALS OF MALAWI IN THE MAJETE WILDLIFE RESERVE","Short Description":"How can we best help African wildlife return to and thrive in their native habitat?","Image Name":"img1.jpg","US Price Range":3725,"UK Price Range":4125,"Location":"Majete Wildlife Reserve, Malawi","Duration":12,"Boating":null,"Digging":null,"Diving":null,"Flat Land Hiking":1,"Snorkeling":1,"Swimming":1,"Uphill Hiking":null},
{"Continent":"Africa","Research Type":"Climate Change","Activity Level":"Very Easy","Title":"ANIMALS OF MALAWI IN THE MAJETE WILDLIFE RESERVE","Short Description":"How can we best help African wildlife return to and thrive in their native habitat?","Image Name":"img1.jpg","US Price Range":3725,"UK Price Range":4125,"Location":"Majete Wildlife Reserve, Malawi","Duration":12,"Boating":null,"Digging":null,"Diving":null,"Flat Land Hiking":null,"Snorkeling":null,"Swimming":null,"Uphill Hiking":null},
{"Continent":"Africa","Research Type":"Climate Change","Activity Level":"Moderate","Title":"ANIMALS OF MALAWI IN THE MAJETE WILDLIFE RESERVE","Short Description":"How can we best help African wildlife return to and thrive in their native habitat?","Image Name":"img1.jpg","US Price Range":3725,"UK Price Range":4125,"Location":"Majete Wildlife Reserve, Malawi","Duration":12,"Boating":null,"Digging":null,"Diving":null,"Flat Land Hiking":null,"Snorkeling":null,"Swimming":null,"Uphill Hiking":null},
{"Continent":"Africa","Research Type":"Climate Change","Activity Level":"Strenuous","Title":"ANIMALS OF MALAWI IN THE MAJETE WILDLIFE RESERVE","Short Description":"How can we best help African wildlife return to and thrive in their native habitat?","Image Name":"img1.jpg","US Price Range":3725,"UK Price Range":4125,"Location":"Majete Wildlife Reserve, Malawi","Duration":12,"Boating":null,"Digging":null,"Diving":null,"Flat Land Hiking":null,"Snorkeling":null,"Swimming":null,"Uphill Hiking":null},
{"Continent":"Africa","Research Type":"Climate Change","Activity Level":"Very Active","Title":"ANIMALS OF MALAWI IN THE MAJETE WILDLIFE RESERVE","Short Description":"How can we best help African wildlife return to and thrive in their native habitat?","Image Name":"img1.jpg","US Price Range":3725,"UK Price Range":4125,"Location":"Majete Wildlife Reserve, Malawi","Duration":12,"Boating":null,"Digging":null,"Diving":null,"Flat Land Hiking":1,"Snorkeling":1,"Swimming":1,"Uphill Hiking":null}]

var Continents = {"Africa":{}, "Antarctica":{}, "North America":{}, "South America":{}, "Europe":{}, "Asia":{}};
var ResearchTypes = {"Wildlife & Ecosystems":[], "Ocean Health":[], "Climate Change":[]};

for (var data in Continents) {
	Continents[data] = ResearchTypes;
}

len = expeditions.length;
for (i = 0; i < len; i++) {
	var con = expeditions[i]["Continent"];
	var res = expeditions[i]["Research Type"];
	Continents[con][res].push(expeditions[i]);
}
