var expeditions = [{"Region":"Africa","Research Type":"Wildlife & Ecosystems","Activity Level":"Moderate","Title":" Animals of Malawi in the Majete Wildlife Reserve","Image Name":"https://s3.amazonaws.com/EarthwatchMedia/ExpeditionAvatars/1075.png","US Price Range":"3725","UK Price Range":null,"Location":"Majete Wildlife Reserve, Malawi","Duration":12,"Boating":null,"Digging":null,"Diving":null,"Flat Land Hiking":1,"Snorkeling":null,"Swimming":null,"Uphill Hiking":1,"Teen":1,"Wildlife":1,"High Temp":1,"Low Temp":null,"Audience":"Adult","Learn More URL":"animals-of-malawi-in-the-majete-wildlife-reserve","Booking URL":1075},
{"Region":"Africa","Research Type":"Wildlife & Ecosystems","Activity Level":"","Title":"Conserving Endangered Rhinos in South Africa","Image Name":"https://s3.amazonaws.com/EarthwatchMedia/ExpeditionAvatars/3156.jpg","US Price Range":"3475","UK Price Range":null,"Location":"Northwest Province, South Africa","Duration":12,"Boating":null,"Digging":null,"Diving":null,"Flat Land Hiking":null,"Snorkeling":null,"Swimming":null,"Uphill Hiking":null,"Teen":null,"Wildlife":null,"High Temp":null,"Low Temp":null,"Audience":"Adult","Learn More URL":"conserving-endangered-rhinos-in-south-africa","Booking URL":3156},
{"Region":"Africa","Research Type":"Wildlife & Ecosystems","Activity Level":"Varies","Title":"Conserving Leopards and Monkeys in South Africa","Image Name":"https://s3.amazonaws.com/EarthwatchMedia/ExpeditionAvatars/2090.jpg","US Price Range":"2775","UK Price Range":null,"Location":"Polokwane, South Africa","Duration":12,"Boating":null,"Digging":null,"Diving":null,"Flat Land Hiking":null,"Snorkeling":null,"Swimming":null,"Uphill Hiking":1,"Teen":null,"Wildlife":1,"High Temp":null,"Low Temp":null,"Audience":"Adult","Learn More URL":"conserving-leopards-and-monkeys-in-south-africa","Booking URL":2090},
{"Region":"Africa","Research Type":"Ocean Health","Activity Level":"","Title":"Coral Communities in the Seychelles","Image Name":"http://s3.amazonaws.com/Earthwatch/ExpeditionAvatars/2095.png","US Price Range":"","UK Price Range":null,"Location":"Curieuse Island, Seychelles","Duration":null,"Boating":null,"Digging":null,"Diving":null,"Flat Land Hiking":null,"Snorkeling":null,"Swimming":null,"Uphill Hiking":null,"Teen":null,"Wildlife":null,"High Temp":null,"Low Temp":null,"Audience":"Adult","Learn More URL":"coral-communities-in-the-seychelles","Booking URL":null},
{"Region":"Africa","Research Type":"Ocean Health","Activity Level":"Easy","Title":"Discovering Sharks in South Africa","Image Name":"https://s3.amazonaws.com/EarthwatchMedia/ExpeditionAvatars/3142.jpg","US Price Range":"2275-3750","UK Price Range":null,"Location":"Walker Bay, South Africa","Duration":7,"Boating":1,"Digging":null,"Diving":null,"Flat Land Hiking":null,"Snorkeling":null,"Swimming":null,"Uphill Hiking":null,"Teen":null,"Wildlife":1,"High Temp":null,"Low Temp":null,"Audience":"Adult","Learn More URL":"discovering-sharks-in-south-africa","Booking URL":3142},
{"Region":"Africa","Research Type":"Wildlife & Ecosystems","Activity Level":"Moderate","Title":"Exploring Lions and their Prey in Kenya","Image Name":"https://s3.amazonaws.com/EarthwatchMedia/ExpeditionAvatars/3127.jpg","US Price Range":"3875","UK Price Range":null,"Location":"Ol Pejeta Conservancy, Kenya","Duration":14,"Boating":null,"Digging":null,"Diving":null,"Flat Land Hiking":1,"Snorkeling":null,"Swimming":null,"Uphill Hiking":null,"Teen":null,"Wildlife":1,"High Temp":1,"Low Temp":null,"Audience":"Adult","Learn More URL":"exploring-lions-and-their-prey-in-kenya","Booking URL":3127},
{"Region":"Africa","Research Type":"Wildlife & Ecosystems","Activity Level":"Strenuous","Title":"Investigating Threats to Chimps in Uganda","Image Name":"https://s3.amazonaws.com/EarthwatchMedia/ExpeditionAvatars/2077.png","US Price Range":"2975","UK Price Range":null,"Location":"Budongo Forest Reserve, Uganda","Duration":12,"Boating":null,"Digging":null,"Diving":null,"Flat Land Hiking":1,"Snorkeling":null,"Swimming":null,"Uphill Hiking":1,"Teen":null,"Wildlife":1,"High Temp":1,"Low Temp":null,"Audience":"Adult","Learn More URL":"investigating-threats-to-chimps-in-uganda","Booking URL":2077},
{"Region":"Africa","Research Type":"Wildlife & Ecosystems","Activity Level":"Moderate","Title":"South African Penguins","Image Name":"https://s3.amazonaws.com/EarthwatchMedia/ExpeditionAvatars/1068.png","US Price Range":"3175","UK Price Range":null,"Location":"Robben Island, Cape Town, South Africa","Duration":12,"Boating":null,"Digging":null,"Diving":null,"Flat Land Hiking":1,"Snorkeling":null,"Swimming":null,"Uphill Hiking":null,"Teen":null,"Wildlife":1,"High Temp":null,"Low Temp":null,"Audience":"Adult","Learn More URL":"south-african-penguins","Booking URL":1068},
{"Region":"Africa","Research Type":"Wildlife & Ecosystems","Activity Level":"Very Active","Title":"Walking with African Wildlife","Image Name":"https://s3.amazonaws.com/EarthwatchMedia/ExpeditionAvatars/2079.png","US Price Range":"3725","UK Price Range":null,"Location":"Hluhluwe-iMfolozi Park, South Africa","Duration":16,"Boating":null,"Digging":null,"Diving":null,"Flat Land Hiking":null,"Snorkeling":null,"Swimming":null,"Uphill Hiking":null,"Teen":null,"Wildlife":null,"High Temp":null,"Low Temp":null,"Audience":"Adult","Learn More URL":"walking-with-african-wildlife","Booking URL":2079},
{"Region":"Asia","Research Type":"Archaeology & Culture","Activity Level":"","Title":"Archaeology of the Mongolian Steppe","Image Name":"https://s3.amazonaws.com/EarthwatchMedia/ExpeditionAvatars/2082.png","US Price Range":"2525-4250","UK Price Range":null,"Location":"Ikh Nart Nature Reserve, Dornogobi Aimag, Mongolia","Duration":9,"Boating":null,"Digging":null,"Diving":null,"Flat Land Hiking":1,"Snorkeling":null,"Swimming":null,"Uphill Hiking":1,"Teen":null,"Wildlife":null,"High Temp":1,"Low Temp":1,"Audience":"Adult","Learn More URL":"archaeology-of-the-mongolian-steppe","Booking URL":2082},
{"Region":"Asia","Research Type":"Climate Change","Activity Level":"","Title":"Butterflies and Bees in the Indian Himalayas","Image Name":"https://s3.amazonaws.com/EarthwatchMedia/ExpeditionAvatars/2078.png","US Price Range":"3075","UK Price Range":null,"Location":"Kullu, Himachal Pradesh, India","Duration":12,"Boating":null,"Digging":null,"Diving":null,"Flat Land Hiking":1,"Snorkeling":null,"Swimming":null,"Uphill Hiking":null,"Teen":null,"Wildlife":null,"High Temp":1,"Low Temp":null,"Audience":"Adult, Teen","Learn More URL":"butterflies-and-bees-in-the-indian-himalayas","Booking URL":2078},
{"Region":"Asia","Research Type":"Climate Change","Activity Level":"","Title":"Climate and Landscape Change in Borneo’s Rainforests","Image Name":"https://s3.amazonaws.com/EarthwatchMedia/ExpeditionAvatars/2088.jpg","US Price Range":"1850","UK Price Range":null,"Location":"Danum Valley, Malaysia","Duration":10,"Boating":null,"Digging":null,"Diving":null,"Flat Land Hiking":1,"Snorkeling":null,"Swimming":null,"Uphill Hiking":1,"Teen":null,"Wildlife":null,"High Temp":1,"Low Temp":null,"Audience":"Adult, Teen","Learn More URL":"climate-and-landscape-change-in-borneos-rainforest","Booking URL":2088},
{"Region":"Asia","Research Type":"Wildlife & Ecosystems","Activity Level":"","Title":"Conserving Tiger and Elephant Habitat in India","Image Name":"https://s3.amazonaws.com/EarthwatchMedia/ExpeditionAvatars/3158.jpg","US Price Range":"3325","UK Price Range":null,"Location":"Uttarakhand, India","Duration":11,"Boating":null,"Digging":null,"Diving":null,"Flat Land Hiking":null,"Snorkeling":null,"Swimming":null,"Uphill Hiking":null,"Teen":null,"Wildlife":null,"High Temp":null,"Low Temp":null,"Audience":"Adult","Learn More URL":"conserving-tiger-and-elephant-habitat-in-india","Booking URL":3158},
{"Region":"Asia","Research Type":"Wildlife & Ecosystems","Activity Level":"","Title":"Wildlife of the Mongolian Steppe","Image Name":"https://s3.amazonaws.com/EarthwatchMedia/ExpeditionAvatars/2083.png","US Price Range":"3375-3400","UK Price Range":null,"Location":"Ikh Nart Nature Reserve, Dornogobi Aimag, Mongolia","Duration":14,"Boating":null,"Digging":null,"Diving":null,"Flat Land Hiking":1,"Snorkeling":null,"Swimming":null,"Uphill Hiking":1,"Teen":null,"Wildlife":1,"High Temp":1,"Low Temp":1,"Audience":"Adult","Learn More URL":"wildlife-of-the-mongolian-steppe","Booking URL":2083},
{"Region":"Australia","Research Type":"Wildlife & Ecosystems","Activity Level":"Very Active","Title":"Conserving Koala Country","Image Name":"https://s3.amazonaws.com/EarthwatchMedia/ExpeditionAvatars/2081.jpg","US Price Range":"3975","UK Price Range":null,"Location":"Great Otway National Park, Victoria, Australia","Duration":10,"Boating":null,"Digging":null,"Diving":null,"Flat Land Hiking":1,"Snorkeling":null,"Swimming":null,"Uphill Hiking":1,"Teen":null,"Wildlife":null,"High Temp":1,"Low Temp":1,"Audience":"Adult","Learn More URL":"conserving-koala-country","Booking URL":2081},
{"Region":"Australia","Research Type":"Ocean Health","Activity Level":"","Title":"Mantas and Sharks of Ningaloo Reef","Image Name":"https://s3.amazonaws.com/EarthwatchMedia/ExpeditionAvatars/3162.jpg","US Price Range":"","UK Price Range":null,"Location":"Coral Bay, Western Australia, Australia","Duration":null,"Boating":1,"Digging":null,"Diving":null,"Flat Land Hiking":null,"Snorkeling":null,"Swimming":null,"Uphill Hiking":null,"Teen":null,"Wildlife":null,"High Temp":null,"Low Temp":null,"Audience":"Adult","Learn More URL":"mantas-and-sharks-of-ningaloo-reef","Booking URL":null},
{"Region":"Australia","Research Type":"Ocean Health","Activity Level":"Very Active","Title":"Recovery of the Great Barrier Reef","Image Name":"https://s3.amazonaws.com/EarthwatchMedia/ExpeditionAvatars/1070.jpg","US Price Range":"2875","UK Price Range":null,"Location":"Orpheus Island, Great Barrier Reef, Australia","Duration":8,"Boating":1,"Digging":null,"Diving":1,"Flat Land Hiking":null,"Snorkeling":1,"Swimming":1,"Uphill Hiking":null,"Teen":null,"Wildlife":null,"High Temp":1,"Low Temp":null,"Audience":"Adult","Learn More URL":"recovery-of-the-great-barrier-reef","Booking URL":1070},
{"Region":"Australia","Research Type":"Wildlife & Ecosystems","Activity Level":"","Title":"Tracking Change In Australia’s Island Wildlife","Image Name":"","US Price Range":"","UK Price Range":null,"Location":"","Duration":null,"Boating":null,"Digging":null,"Diving":null,"Flat Land Hiking":null,"Snorkeling":null,"Swimming":null,"Uphill Hiking":null,"Teen":null,"Wildlife":null,"High Temp":null,"Low Temp":null,"Audience":"","Learn More URL":"","Booking URL":null},
{"Region":"Australia","Research Type":"Wildlife & Ecosystems","Activity Level":"Moderate","Title":"Wildlife of Australia’s Rainforest","Image Name":"https://s3.amazonaws.com/EarthwatchMedia/ExpeditionAvatars/2080.png","US Price Range":"2050-3375","UK Price Range":null,"Location":"Wet Tropics World Heritage Area, North Queensland, Australia","Duration":7,"Boating":null,"Digging":null,"Diving":null,"Flat Land Hiking":null,"Snorkeling":null,"Swimming":null,"Uphill Hiking":1,"Teen":null,"Wildlife":null,"High Temp":1,"Low Temp":null,"Audience":"Adult","Learn More URL":"wildlife-of-australias-rainforest","Booking URL":2080},
{"Region":"Central America & Caribbean","Research Type":"Climate Change","Activity Level":"Moderate","Title":"Climate Change and Caterpillars in Costa Rica","Image Name":"https://s3.amazonaws.com/EarthwatchMedia/ExpeditionAvatars/2067.png","US Price Range":"2575","UK Price Range":null,"Location":"La Selva Biological Station & Tirimbina, Costa Rica","Duration":9,"Boating":null,"Digging":null,"Diving":null,"Flat Land Hiking":1,"Snorkeling":null,"Swimming":null,"Uphill Hiking":1,"Teen":null,"Wildlife":null,"High Temp":1,"Low Temp":null,"Audience":"Adult","Learn More URL":"climate-change-and-caterpillars-in-costa-rica","Booking URL":2067},
{"Region":"Central America & Caribbean","Research Type":"Wildlife & Ecosystems","Activity Level":"Moderate","Title":"Conserving Wild Bees and Other Pollinators of Costa Rica","Image Name":"https://s3.amazonaws.com/EarthwatchMedia/ExpeditionAvatars/3155.jpg","US Price Range":"1950-3475","UK Price Range":null,"Location":"San Luis de Monteverde and/or Puerto Jimenez, Costa Rica","Duration":7,"Boating":null,"Digging":null,"Diving":null,"Flat Land Hiking":null,"Snorkeling":null,"Swimming":null,"Uphill Hiking":null,"Teen":null,"Wildlife":null,"High Temp":null,"Low Temp":null,"Audience":"Adult","Learn More URL":"conserving-wild-bees-and-other-pollinators-of-costa-rica","Booking URL":3155},
{"Region":"Central America & Caribbean","Research Type":"Ocean Health","Activity Level":"Moderate","Title":"Costa Rican Sea Turtles","Image Name":"https://s3.amazonaws.com/EarthwatchMedia/ExpeditionAvatars/2107.jpg","US Price Range":"2175-2875","UK Price Range":null,"Location":"Parque Nacional Marino Las Baulas, Guanacaste Province, Costa Rica","Duration":9,"Boating":null,"Digging":null,"Diving":null,"Flat Land Hiking":1,"Snorkeling":null,"Swimming":null,"Uphill Hiking":null,"Teen":null,"Wildlife":null,"High Temp":1,"Low Temp":null,"Audience":"Adult","Learn More URL":"costa-rican-sea-turtles","Booking URL":2107},
{"Region":"Central America & Caribbean","Research Type":"Wildlife & Ecosystems","Activity Level":"Moderate","Title":"Exploring an Active Volcano in Nicaragua","Image Name":"https://s3.amazonaws.com/EarthwatchMedia/ExpeditionAvatars/2099.jpg","US Price Range":"2500-3425","UK Price Range":null,"Location":"Masaya Volcano, Nicaragua","Duration":7,"Boating":null,"Digging":null,"Diving":null,"Flat Land Hiking":1,"Snorkeling":null,"Swimming":null,"Uphill Hiking":1,"Teen":null,"Wildlife":null,"High Temp":1,"Low Temp":null,"Audience":"Adult","Learn More URL":"exploring-an-active-volcano-in-nicaragua","Booking URL":2099},
{"Region":"Central America & Caribbean","Research Type":"Ocean Health","Activity Level":"Moderate","Title":"Helping Endangered Corals in Little Cayman","Image Name":"https://s3.amazonaws.com/EarthwatchMedia/ExpeditionAvatars/3146.jpg","US Price Range":"2750-3050","UK Price Range":null,"Location":"Little Cayman, Cayman Islands","Duration":7,"Boating":1,"Digging":null,"Diving":null,"Flat Land Hiking":null,"Snorkeling":1,"Swimming":1,"Uphill Hiking":null,"Teen":1,"Wildlife":null,"High Temp":1,"Low Temp":null,"Audience":"Adult, Teen","Learn More URL":"helping-endangered-corals-in-little-cayman","Booking URL":3146},
{"Region":"Central America & Caribbean","Research Type":"Wildlife & Ecosystems","Activity Level":"Very Active","Title":"Monitoring Ocelots in Trinidad","Image Name":"https://s3.amazonaws.com/EarthwatchMedia/ExpeditionAvatars/3159.jpg","US Price Range":"2575-2825","UK Price Range":null,"Location":"Multiple locations in Trinidad’s Forest and Agriculture Lands, Trinidad and Tobago","Duration":8,"Boating":null,"Digging":null,"Diving":null,"Flat Land Hiking":null,"Snorkeling":null,"Swimming":null,"Uphill Hiking":null,"Teen":null,"Wildlife":null,"High Temp":null,"Low Temp":null,"Audience":"Adult","Learn More URL":"monitoring-ocelots-in-trinidad","Booking URL":3159},
{"Region":"Central America & Caribbean","Research Type":"Wildlife & Ecosystems","Activity Level":"Very Active","Title":"Puerto Rico’s Rainforest","Image Name":"https://s3.amazonaws.com/EarthwatchMedia/ExpeditionAvatars/2085.jpg","US Price Range":"2075-2475","UK Price Range":null,"Location":"Las Casas de la Selva, Patillas, Puerto Rico","Duration":10,"Boating":null,"Digging":null,"Diving":null,"Flat Land Hiking":null,"Snorkeling":null,"Swimming":null,"Uphill Hiking":1,"Teen":1,"Wildlife":null,"High Temp":null,"Low Temp":null,"Audience":"Adult, Teen","Learn More URL":"puerto-ricos-rainforest","Booking URL":2085},
{"Region":"Central America & Caribbean","Research Type":"Ocean Health","Activity Level":"Easy","Title":"Safeguarding Whales and Dolphins in Costa Rica","Image Name":"https://s3.amazonaws.com/EarthwatchMedia/ExpeditionAvatars/2073.png","US Price Range":"1975-2275","UK Price Range":null,"Location":"Golfo Dulce, Costa Rica","Duration":9,"Boating":1,"Digging":null,"Diving":null,"Flat Land Hiking":null,"Snorkeling":null,"Swimming":null,"Uphill Hiking":null,"Teen":1,"Wildlife":null,"High Temp":1,"Low Temp":null,"Audience":"Adult, Teen","Learn More URL":"safeguarding-whales-and-dolphins-in-costa-rica","Booking URL":2073},
{"Region":"Central America & Caribbean","Research Type":"Ocean Health","Activity Level":"Moderate","Title":"Shark Conservation in Belize","Image Name":"https://s3.amazonaws.com/EarthwatchMedia/ExpeditionAvatars/1073.png","US Price Range":"2795-3100","UK Price Range":null,"Location":"South Water Caye or Glover’s Reef, Belize","Duration":8,"Boating":1,"Digging":null,"Diving":null,"Flat Land Hiking":null,"Snorkeling":null,"Swimming":null,"Uphill Hiking":null,"Teen":1,"Wildlife":1,"High Temp":1,"Low Temp":null,"Audience":"Adult, Teen","Learn More URL":"shark-conservation-in-belize","Booking URL":1073},
{"Region":"Central America & Caribbean","Research Type":"Climate Change","Activity Level":"","Title":"Sustainable Agriculture & Water Quality in the Wetlands of Mexico","Image Name":"","US Price Range":"","UK Price Range":null,"Location":"","Duration":null,"Boating":null,"Digging":null,"Diving":null,"Flat Land Hiking":null,"Snorkeling":null,"Swimming":null,"Uphill Hiking":null,"Teen":null,"Wildlife":null,"High Temp":null,"Low Temp":null,"Audience":"","Learn More URL":"","Booking URL":null},
{"Region":"Central America & Caribbean","Research Type":"Ocean Health","Activity Level":"","Title":"Tracking Sea Turtles in The Bahamas","Image Name":"https://s3.amazonaws.com/EarthwatchMedia/ExpeditionAvatars/3123.png","US Price Range":"2850-3075","UK Price Range":null,"Location":"Cape Eleuthera, Bahamas","Duration":9,"Boating":1,"Digging":null,"Diving":null,"Flat Land Hiking":null,"Snorkeling":1,"Swimming":1,"Uphill Hiking":null,"Teen":1,"Wildlife":null,"High Temp":1,"Low Temp":null,"Audience":"Adult, Teen","Learn More URL":"tracking-sea-turtles-in-the-bahamas","Booking URL":3123},
{"Region":"Europe","Research Type":"Climate Change","Activity Level":"","Title":"Climate Change in Wytham Woods","Image Name":"https://s3.amazonaws.com/EarthwatchMedia/ExpeditionAvatars/1064.jpg","US Price Range":"135","UK Price Range":null,"Location":"Wytham, Oxfordshire, United Kingdom","Duration":1,"Boating":null,"Digging":null,"Diving":null,"Flat Land Hiking":1,"Snorkeling":null,"Swimming":null,"Uphill Hiking":null,"Teen":null,"Wildlife":null,"High Temp":null,"Low Temp":null,"Audience":"Adult","Learn More URL":"climate-change-in-wytham-woods","Booking URL":1064},
{"Region":"Europe","Research Type":"Archaeology & Culture","Activity Level":"Moderate","Title":"Excavating the Roman Empire in Britain","Image Name":"http://s3.amazonaws.com/Earthwatch/ExpeditionAvatars/1069.png?AWSAccessKeyId=AKIAJZKL4GAMQB4XVQ5A&Expires=2145916800&Signature=PcfiPNGM%2FknaU7OwV70M6582J30%3D","US Price Range":"875-2995","UK Price Range":null,"Location":"South Shields, Tyneside, United Kingdom","Duration":6,"Boating":null,"Digging":1,"Diving":null,"Flat Land Hiking":1,"Snorkeling":null,"Swimming":null,"Uphill Hiking":null,"Teen":1,"Wildlife":1,"High Temp":null,"Low Temp":null,"Audience":"Adult, Teen","Learn More URL":"excavating-the-roman-empire-in-britain","Booking URL":1069},
{"Region":"Europe","Research Type":"Ocean Health","Activity Level":"Moderate","Title":"Tracking Dolphins in the Adriatic Sea","Image Name":"https://s3.amazonaws.com/EarthwatchMedia/ExpeditionAvatars/3149.jpg","US Price Range":"2695","UK Price Range":null,"Location":"Piran, Slovenia","Duration":10,"Boating":1,"Digging":null,"Diving":null,"Flat Land Hiking":1,"Snorkeling":null,"Swimming":null,"Uphill Hiking":null,"Teen":null,"Wildlife":null,"High Temp":null,"Low Temp":null,"Audience":"Adult","Learn More URL":"tracking-dolphins-in-the-adriatic-sea","Booking URL":3149},
{"Region":"Europe","Research Type":"Archaeology & Culture","Activity Level":"Moderate","Title":"Unearthing Ancient History in Tuscany","Image Name":"https://s3.amazonaws.com/EarthwatchMedia/ExpeditionAvatars/2070.jpg","US Price Range":"1895-3525","UK Price Range":null,"Location":"Baratti and Populonia Archaeological Park, Piombino, Tuscany, Italy","Duration":7,"Boating":null,"Digging":1,"Diving":null,"Flat Land Hiking":1,"Snorkeling":null,"Swimming":null,"Uphill Hiking":null,"Teen":1,"Wildlife":null,"High Temp":1,"Low Temp":null,"Audience":"Adult, Teen","Learn More URL":"unearthing-ancient-history-in-tuscany","Booking URL":2070},
{"Region":"Europe","Research Type":"Climate Change","Activity Level":"Strenuous","Title":"Wildlife in the Changing French Pyrenees","Image Name":"https://s3.amazonaws.com/EarthwatchMedia/ExpeditionAvatars/3139.jpg","US Price Range":"","UK Price Range":null,"Location":"Aspet, France","Duration":9,"Boating":null,"Digging":null,"Diving":null,"Flat Land Hiking":1,"Snorkeling":null,"Swimming":null,"Uphill Hiking":1,"Teen":null,"Wildlife":1,"High Temp":1,"Low Temp":null,"Audience":"Adult","Learn More URL":"wildlife-in-the-changing-french-pyrenees","Booking URL":null},
{"Region":"North America","Research Type":"Climate Change","Activity Level":"Moderate","Title":"Climate Change at the Arctic’s Edge","Image Name":"https://s3.amazonaws.com/EarthwatchMedia/ExpeditionAvatars/2091.jpg","US Price Range":"2975-3725","UK Price Range":null,"Location":"Churchill, Manitoba, Canada, North America & Arctic","Duration":"7+","Boating":null,"Digging":null,"Diving":null,"Flat Land Hiking":1,"Snorkeling":null,"Swimming":null,"Uphill Hiking":null,"Teen":1,"Wildlife":1,"High Temp":null,"Low Temp":1,"Audience":"Adult, Teen","Learn More URL":"climate-change-at-the-arctics-edge","Booking URL":2091},
{"Region":"North America","Research Type":"Climate Change","Activity Level":"","Title":"Climate Change in the MacKenzie Mountains","Image Name":"https://s3.amazonaws.com/EarthwatchMedia/ExpeditionAvatars/2100.png","US Price Range":"5725","UK Price Range":null,"Location":"Mackenzie Mountains, Northwest Territory, Canada","Duration":11,"Boating":null,"Digging":null,"Diving":null,"Flat Land Hiking":1,"Snorkeling":null,"Swimming":null,"Uphill Hiking":1,"Teen":null,"Wildlife":1,"High Temp":null,"Low Temp":1,"Audience":"Adult","Learn More URL":"climate-change-in-the-mackenzie-mountains","Booking URL":2100},
{"Region":"North America","Research Type":"Climate Change","Activity Level":"Varies","Title":"Exploring Boston’s Urban Forest","Image Name":"https://s3.amazonaws.com/EarthwatchMedia/ExpeditionAvatars/1062.jpg","US Price Range":"15","UK Price Range":null,"Location":"Boston, United States","Duration":1,"Boating":null,"Digging":null,"Diving":null,"Flat Land Hiking":1,"Snorkeling":null,"Swimming":null,"Uphill Hiking":null,"Teen":1,"Wildlife":null,"High Temp":null,"Low Temp":null,"Audience":"Adult","Learn More URL":"exploring-bostons-urban-forest","Booking URL":1062},
{"Region":"North America","Research Type":"Climate Change","Activity Level":"Moderate","Title":"Exploring Rising Tides in South Carolina","Image Name":"https://s3.amazonaws.com/EarthwatchMedia/ExpeditionAvatars/3145.jpg","US Price Range":"","UK Price Range":null,"Location":"Winyah Bay, South Carolina, United States","Duration":null,"Boating":null,"Digging":null,"Diving":null,"Flat Land Hiking":1,"Snorkeling":null,"Swimming":null,"Uphill Hiking":null,"Teen":1,"Wildlife":null,"High Temp":1,"Low Temp":null,"Audience":"Adult, Teen","Learn More URL":"exploring-rising-tides-in-south-carolina","Booking URL":3145},
{"Region":"North America","Research Type":"Wildlife & Ecosystems","Activity Level":"Moderate","Title":"Following Flammulated Owls in the Western U.S.","Image Name":"https://s3.amazonaws.com/EarthwatchMedia/ExpeditionAvatars/3153.jpg","US Price Range":"2050-3150","UK Price Range":null,"Location":"Snow Basin, Utah or Portal, Arizona, United States","Duration":7,"Boating":null,"Digging":null,"Diving":null,"Flat Land Hiking":null,"Snorkeling":null,"Swimming":null,"Uphill Hiking":null,"Teen":null,"Wildlife":null,"High Temp":null,"Low Temp":null,"Audience":"Adult","Learn More URL":"following-flammulated-owls-in-the-western-us","Booking URL":3153},
{"Region":"North America","Research Type":"Wildlife & Ecosystems","Activity Level":"","Title":"Protecting Whooping Cranes and Coastal Habitats in Texas","Image Name":"https://s3.amazonaws.com/EarthwatchMedia/ExpeditionAvatars/3157.jpg","US Price Range":"2175","UK Price Range":null,"Location":"Aransas National Wildlife Refuge, Austwell, Texas, United States","Duration":7,"Boating":null,"Digging":null,"Diving":null,"Flat Land Hiking":null,"Snorkeling":null,"Swimming":null,"Uphill Hiking":null,"Teen":null,"Wildlife":null,"High Temp":null,"Low Temp":null,"Audience":"Adult","Learn More URL":"protecting-whooping-cranes-and-coastal-habitats-in-texas","Booking URL":3157},
{"Region":"North America","Research Type":"Climate Change","Activity Level":"Strenuous","Title":"Saving Joshua Tree’s Desert Species","Image Name":"https://s3.amazonaws.com/EarthwatchMedia/ExpeditionAvatars/3144.jpg","US Price Range":"2195-3075","UK Price Range":null,"Location":"Joshua Tree National Park, United States","Duration":7,"Boating":null,"Digging":null,"Diving":null,"Flat Land Hiking":1,"Snorkeling":null,"Swimming":null,"Uphill Hiking":1,"Teen":1,"Wildlife":1,"High Temp":1,"Low Temp":null,"Audience":"Adult","Learn More URL":"saving-joshua-trees-desert-species","Booking URL":3144},
{"Region":"North America","Research Type":"Climate Change","Activity Level":"","Title":"Sea to Trees at Acadia National Park","Image Name":"https://s3.amazonaws.com/EarthwatchMedia/ExpeditionAvatars/3151.jpg","US Price Range":"1975-2275","UK Price Range":null,"Location":"Acadia National Park, Maine, United States","Duration":7,"Boating":null,"Digging":null,"Diving":null,"Flat Land Hiking":1,"Snorkeling":null,"Swimming":null,"Uphill Hiking":1,"Teen":1,"Wildlife":null,"High Temp":null,"Low Temp":null,"Audience":"Adult, Teen","Learn More URL":"climate-change-sea-to-trees-at-acadia-national-park","Booking URL":3151},
{"Region":"North America","Research Type":"Wildlife & Ecosystems","Activity Level":"Strenuous","Title":"Tracking Fire and Wolves through the Canadian Rockies","Image Name":"https://s3.amazonaws.com/EarthwatchMedia/ExpeditionAvatars/3148.png","US Price Range":"2350-3150","UK Price Range":null,"Location":"Waterton Lakes National Park, Canada","Duration":7,"Boating":null,"Digging":null,"Diving":null,"Flat Land Hiking":1,"Snorkeling":null,"Swimming":null,"Uphill Hiking":1,"Teen":null,"Wildlife":1,"High Temp":null,"Low Temp":1,"Audience":"Adult","Learn More URL":"tracking-fire-and-wolves-through-the-canadian-rockies","Booking URL":3148},
{"Region":"North America","Research Type":"Archaeology & Culture","Activity Level":"Easy","Title":"Uncovering the Mysteries of Ancient Colorado","Image Name":"https://s3.amazonaws.com/EarthwatchMedia/ExpeditionAvatars/2097.png","US Price Range":"1875-3225","UK Price Range":null,"Location":"Cortez, Colorado, United States","Duration":7,"Boating":null,"Digging":1,"Diving":null,"Flat Land Hiking":1,"Snorkeling":null,"Swimming":null,"Uphill Hiking":null,"Teen":1,"Wildlife":null,"High Temp":null,"Low Temp":null,"Audience":"Adult, Teen","Learn More URL":"uncovering-the-mysteries-of-ancient-colorado","Booking URL":2097},
{"Region":"North America","Research Type":"Ocean Health","Activity Level":"Easy","Title":"Whales and Dolphins Under the California Sun","Image Name":"https://s3.amazonaws.com/EarthwatchMedia/ExpeditionAvatars/2103.png","US Price Range":"2375-3295","UK Price Range":null,"Location":"Dana Point and Catalina Island, California, United States","Duration":7,"Boating":1,"Digging":null,"Diving":null,"Flat Land Hiking":1,"Snorkeling":null,"Swimming":null,"Uphill Hiking":null,"Teen":1,"Wildlife":null,"High Temp":null,"Low Temp":null,"Audience":"Adult, Teen","Learn More URL":"whales-and-dolphins-under-the-california-sun","Booking URL":2103},
{"Region":"South America","Research Type":"Wildlife & Ecosystems","Activity Level":"Varies","Title":"Amazon Riverboat Exploration","Image Name":"https://s3.amazonaws.com/EarthwatchMedia/ExpeditionAvatars/1065.png","US Price Range":"2575-3675","UK Price Range":null,"Location":"Samiria River, Peru","Duration":8,"Boating":1,"Digging":null,"Diving":null,"Flat Land Hiking":1,"Snorkeling":null,"Swimming":null,"Uphill Hiking":null,"Teen":null,"Wildlife":null,"High Temp":null,"Low Temp":null,"Audience":"Adult","Learn More URL":"amazon-riverboat-exploration","Booking URL":1065},
{"Region":"South America","Research Type":"Wildlife & Ecosystems","Activity Level":"Moderate","Title":"Trailing Penguins in Patagonia","Image Name":"https://s3.amazonaws.com/EarthwatchMedia/ExpeditionAvatars/3150.jpg","US Price Range":"2450-2500","UK Price Range":null,"Location":"Chubut, Patagonia, Argentina","Duration":7,"Boating":null,"Digging":null,"Diving":null,"Flat Land Hiking":1,"Snorkeling":null,"Swimming":null,"Uphill Hiking":null,"Teen":null,"Wildlife":null,"High Temp":null,"Low Temp":1,"Audience":"Adult","Learn More URL":"trailing-penguins-in-patagonia","Booking URL":3150}];

var Continents = {"Africa":{}, "North America":{}, "South America":{}, "Europe":{}, "Asia":{}, "Central America & Caribbean":{}, "Australia":{} };
var ResearchTypes = {"Wildlife & Ecosystems":[], "Ocean Health":[], "Climate Change":[], "Archaeology & Culture":[]};

for (var data in Continents) {
	Continents[data] = ResearchTypes;
}

len = expeditions.length;
for (i = 0; i < len; i++) {
	var con = expeditions[i]["Region"];
	var res = expeditions[i]["Research Type"];
	Continents[con][res].push(expeditions[i]);
}
